name: Create exe, zip files for release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install Microsoft C++ Build Tools
      run: |
        choco install visualcpp-build-tools --yes

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install greenlet
        pip install -r requirements.txt
        

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install 7-Zip
      run: choco install 7zip

    - name: Create standalone executable
      run: pyinstaller --noconsole --onefile --name=StartGG_Set_Social --hidden-import=babel.numbers main.py

    - name: Create exe zip bundle
      run: |
        7z a 'StartGG_Set_Social.zip' './dist/StartGG_Set_Social.exe'
        7z a 'StartGG_Set_Social.zip' './templates/game_hashtags.yaml' -r -p'./templates/'
        7z a 'StartGG_Set_Social.zip' './templates/tweets.yaml' -r -p'./templates/'

    - name: Install GitHub CLI
      run: |
        choco install gh

    - name: Create GitHub Release and Upload Zip
      run: |
        echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        gh release create ${{ github.ref }} StartGG_Set_Social.zip --title "Release ${{ github.ref }}" --notes "Release notes for ${{ github.ref }}"
