name: Zips pre-created release

on:
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: choco install 7zip

    - name: Create exe zip bundle
      run: |
        7z a 'StartGG_Set_Social.zip' './dist/StartGGSetSocial.exe'
        7z a 'StartGG_Set_Social.zip' './templates/game_hashtags.yaml' -r -p'./templates/'
        7z a 'StartGG_Set_Social.zip' './templates/tweets.yaml' -r -p'./templates/'

    - name: Install GitHub CLI
      run: |
        choco install gh

    - name: Create GitHub Release and Upload Zip
      run: |
        echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        gh release create "${{ github.ref_name }}" StartGG_Set_Social.zip --title "Release ${{ github.ref_name }}" --notes "Release notes for ${{ github.ref_name }}"
